### ISSUE TITLE
Making error handlers more efficient.

### ISSUE THREAD

**Issue by nvx0** [French-Cat/decrashify#1]
Hey! This is an great idea for an Lib. I have been wondering if it's possible to add more efficient ways of catching the errors, like for ex. saving it to an file. Also I would prefer adding more kinds of handlers like for warnings and all kind of stuff. 

If you don't mind Ill be creating and PR soon.

Thanks.

**Comment by French-Cat** [comment]
Hey nvx0! I've been wondering how I could expand and improve this project. I think your ideas are great and I would love to see what you can come up with.
- FRCat

**Comment by French-Cat** [comment]
Closing this for now, Feel free to reopen at anytime 👍
